### ISSUE TITLE
kannel not starting up and no kannel.conf

### ISSUE THREAD

**Issue by edvalbuena** [ictinnovations/ictdialer#10]
It seems that kannel.conf does not exist on the installation 
 kannel.conf -> /usr/ictcore/etc/kannel/kannel.conf
but it does not have any kannel.conf on that folder.

any chance you guys forgot about it?

**Comment by ICTKashif** [comment]
For Kannel Service, first you need to configure SMPP / kannel based account in ICTDialer and then restart the kannel service

**Comment by telecomunicazioni** [comment]
Firstly I have thinked to copy /etc/kannel/kannel.conf.backup to /etc/kannel/kannel.conf and kannel service started.
After I have thinked to clean kannel.conf when I discovered it's a link to /usr/ictcore/etc/kannel/kannel.conf. Even cleaning the file, kannel doesn't works. I have added a provider but kannel.conf is always empty even restarting the service
