### ISSUE TITLE
not dialing out

### ISSUE THREAD

**Issue by Ramzu** [ictinnovations/ictdialer#14]
Hi. I think I have the SIP credentials entered correctly but it is not calling out. I did leave the prefix blank as I don't know what that means

**Comment by telecomunicazioni** [comment]
pls try to check on freeswitch console

fs_cli

**Comment by ICTKashif** [comment]
Please check ICTCore log file and Freesiwtch SIP logs,

```
/usr/ictcore/log/ictcore.log
```
