### ISSUE TITLE
The requested URL /ictdailer was not found on this server.

### ISSUE THREAD

**Issue by amit1bhatt** [ictinnovations/ictdialer#18]
hello Team
not able to access login page , after installation .

**Comment by ICTKashif** [comment]
Please let us know, facing issue with login information or unable to open ICTDialer URL on web browser

**Comment by amit1bhatt** [comment]
before i was unable to see ICT Dialer home page but after that i copy 
/usr/ictdialer folder into /var/www/html/ and after that successfully access web page .. 

now everything fine but unable to upload contact via CSV file , please help me
