### ISSUE TITLE
Voice Campaign

### ISSUE THREAD

**Issue by Ray-mtl** [ictinnovations/ictdialer#22]
Hello, 
I have installed ictdialer,  trunk is setup, uploaded a recording, which is working fine if i use Transmission voice call to 1 destination
**The issue is after creating a campaign, uploaded a contact list and click on START the campaign, nothing happens.
no logs anywhere,   nothing happens in the freeswitch cli.**
Can you please tell me what i am missing out on?
Thank you

**Comment by ICTKashif** [comment]
Please share ICTCore logs and apache logs 

ICTCore log file path : /usr/ictcore/logs/ictcore.log
Apache log file path : /var/log/httpd/error_log

**Comment by Ray-mtl** [comment]
in ictcore.log  all i you have is this .
[2019-08-30 14:22:58] [27551] [WARNING] Session write failed
[2019-08-30 14:22:58] [27296] [WARNING] Session write failed
[2019-08-30 14:22:58] [7084] [WARNING] Session write failed
[2019-08-30 14:23:00] [7057] [WARNING] Session write failed

httpd/error_log
there is no error , all seems fine.
