### ISSUE TITLE
ictfax web login

### ISSUE THREAD

**Issue by jer612** [ictinnovations/ictdialer#23]
Hello, have  issue with ictfax  when try to login  http://yourdomain/ictfax using : 
Default Username : admin@ictcore.org
Default Password : helloAdmin
I get "Login/Email combination is not correct, please try again

files /etc/ictcore.conf and /etc/odbc.ini  modify  .
how can i manage it 
Regards

**Comment by ICTKashif** [comment]
Please make sure database information correctly entered in theses file

`/etc/ictcore.conf and /etc/odbc.ini`

**Comment by jer612** [comment]
Hello
On Both of the files db name  parameter  "ictfax" configure
The user and password parameters allso changed to be similar.
*On odbc.ini file under [db]
Should I change any other parameters ? 
Br

**Comment by korithi** [comment]
I have the same problem. Can you please help?

**Comment by ICTKashif** [comment]
You just need to enter your database information, like database name, database username and password.
