### ISSUE TITLE
Wrong  File location

### ISSUE THREAD

**Issue by gudge25** [ictinnovations/ictdialer#24]
When ictdialer trying to playback file it is using wrong PATH

EXECUTE sofia/ictcore/380669197533 playback(/tmp/recordingpQ9dYz.wave)
2020-04-01 08:32:00.123845 [ERR] switch_core_file.c:272 Invalid file format [wave] for [/tmp/recordingpQ9dYz.wave]!

I can find PATH  manually
[root@dialer ~]# find / -name recordingpQ9dYz.wave
/tmp/systemd-private-96846f45f1fe42f882d02d83f4963cb8-httpd.service-qAQ0j/tmp/recordingpQ9dYz.wave

**Comment by ICTKashif** [comment]
We have closed the ICTDialer project, You can use ICTBroadcast instead of ICTDialer. please visit this link for more details

https://www.ictbroadcast.com/ictbroadcast-vs-ictdialer-comparison-between-autodialers
https://www.ictbroadcast.com/
