### ISSUE TITLE
Where is ICTDialer 3.0

### ISSUE THREAD

**Issue by dedayoa** [ictinnovations/ictdialer#6]
Hi,
I'm assuming ICTDialer 3.0 is new, however this repo has not been updated in a while.

I'm having issues creating contact groups - specifically, I get HTTP Error 415 (Unsupported Media Type) when I attempt to upload a CSV file.

Since this is open source, I was hoping I'd be able to trace the problem by looking into the code.

**Comment by mcj78** [comment]
Hi dedayoa

Can I ask how you managed to install ICTDialer 3.0 as i haven't been able to install, could you let me know what steps you took as the guide is useless.

Thanks In advance

**Comment by dedayoa** [comment]
Hi mcj78,

I followed the instruction at http://www.ictdialer.org/installation-guide.

I've had to uninstall the application as I couldn't get it to work 
(specifically uploading the contact list/group)...and the developers 
seemed more interested in closing my issue than working with me to 
resolve the problem.

All the best!

**Comment by simplesunny** [comment]
I installed the ICT3.0 but the same issue with uploading the file.. "415 Unsupported Media Type"

**Comment by ICTKashif** [comment]
Please use the .wav file, You can convert online from https://audio.online-convert.com/convert-to-wav

**Comment by simplesunny** [comment]
> Please use the .wav file, You can convert online from https://audio.online-convert.com/convert-to-wav

I am getting this error "415 Unsupported Media Type" while uploading correct format of CSV
