### ISSUE TITLE
Logging In

### ISSUE THREAD

**Issue by csmoot79** [ictinnovations/ictdialer#8]
After doing a vanilla install I am unable to use the default admin and password provided to access the ictdialer page. I get unknown combo is there a terminal based solution to set an email and password to log in? or has the defaults possibly have changed?

**Comment by commiodev** [comment]
Same issue on a CentOS 7 install. 

http://www.ictdialer.org/installation-guide
"
Now visit http://yourdomain/ictdialer in your browser

Default Username : admin@ictcore.org
Default Password : helloAdmin
"

**Comment by jacqueshenning** [comment]
Same issue here, vanilla install.
I can see from the error log that there is a issue with: /usr/ictcore/core/lib/DB.php
` PHP Fatal error:  Uncaught exception 'ICT\\Core\\CoreException' with message 'Unable to select database' in /usr/ictcore/core/lib/DB.php:32\nStack trace:\n#0 /usr/ictcore/core/lib/init.php(49): ICT\\Core\\DB::connect()\n#1 /usr/ictcore/core/Core.php(16): require_once('/usr/ictcore/co...')\n#2 /usr/ictcore/wwwroot/index.php(18): include_once('/usr/ictcore/co...')\n#3 {main}\n  thrown in /usr/ictcore/core/lib/DB.php on line 32, referer:`

**Comment by misua** [comment]
if you look at the mysql db, the created database is  ictdialer

looking at /usr/ictcore/etc/ictcore.conf in  [db] section

name = ictcore (change this to ictdialer)

try to check /usr/ictcore/etc/odbc.ini too


the url to go is http://192.168.0.50/ictcore(not ictdialer as per manual)

i just wonder why call this ictdialer. if i cant auto dial? it seem to have a broadcast only system.
